apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: js
  description: Everything under JS
spec:
  owner: jonshaffer
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: personal
  description: The personal projects of JS
spec:
  owner: jonshaffer
  domain: js
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: js-data
spec:
  type: url
  targets:
    - https://github.com/jonshaffer/blog/blob/main/catalog-info.yaml
    - https://github.com/jonshaffer/pkm/blob/main/catalog-info.yaml
