---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jonshaffer
spec:
  profile:
    displayName: Jon Shaffer
    email: jon@hyperfluidsolutions.com
    picture: https://avatars.githubusercontent.com/u/1992760?v=4
  memberOf: [systmms, hyperfluid, jonshaffer]
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: js
  description: Everything under JS
spec:
  owner: user:default/jonshaffer
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: personal
  description: The personal projects of JS
spec:
  owner: user:default/jonshaffer
  domain: js
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: js-data
spec:
  type: url
  targets:
    - https://github.com/jonshaffer/blog/blob/main/catalog-info.yaml
    - https://github.com/jonshaffer/pkm/blob/main/catalog-info.yaml
    - https://github.com/jonshaffer/resume/blob/main/catalog-info.yaml
    - https://github.com/jonshaffer/swrpg/blob/main/catalog-info.yaml
---
